/**
 * Shared canonical types. Provider implementations map their raw
 * responses onto these shapes so the rest of the app stays clean.
 */

export interface UserProfile {
  fullName: string;
  headline?: string;
  seniority: 'junior' | 'mid' | 'senior' | 'staff' | 'principal';
  yearsExperience: number;
  location?: string;
  skills: string[];
  experience: {
    company: string;
    title: string;
    from: string;
    to: string;
    bullets: string[];
  }[];
  education?: {
    school: string;
    degree: string;
    year?: string;
  }[];
  links?: {
    linkedin?: string;
    github?: string;
    portfolio?: string;
    email?: string;
    phone?: string;
  };
}

export interface UserPreferences {
  locations: string[];
  workModes: ('remote' | 'hybrid' | 'onsite' | 'any')[];
  targetCtc?: string;
  /**
   * User's *current* annual compensation — baseline for the salary-hike
   * calculation shown on each match card. Free-form text ("18L", "22
   * LPA", "$140k"); parsed by parseCtcToNumber() when we need the
   * numeric value.
   */
  currentCtc?: string;
  phone?: string;
  noticePeriod?: string;
  notes?: string;
  emailFrequency: 'daily' | '2days' | 'weekly' | 'realtime' | 'paused';
  emailTime: string; // HH:MM
  timezone: string;
}

export interface JobPosting {
  id: string;               // namespaced: 'adzuna:123' / 'gh:razorpay:456'
  source: 'adzuna' | 'jooble' | 'greenhouse' | 'lever' | 'jsearch' | string;
  title: string;
  company: string;
  location: string;
  description: string;
  url: string;
  postedAt: string;         // ISO
  salary?: { min: number; max: number; currency: string; cadence: 'monthly' | 'yearly' };
  workMode: 'remote' | 'hybrid' | 'onsite' | 'unknown';
  keywords?: string[];
}

export interface TailoredResume {
  summary: string;
  highlightedSkills: string[];
  experienceBullets: { company: string; title: string; bullets: string[] }[];
  rationale: string;
  removedSections: string[];
}

/**
 * A tailored cover letter for one specific job posting. The renderers
 * add the candidate's name/contact header, date, and signature — this
 * holds only the parts Claude writes.
 */
export interface CoverLetter {
  greeting: string;     // e.g. "Dear Hiring Team,"
  paragraphs: string[]; // 3-4 body paragraphs
  closing: string;      // e.g. "Warm regards,"
}

export interface Referrer {
  name: string;
  role: string;
  linkedinUrl?: string;
  sharedContext?: string; // "worked at TechFlow 2021-23"
}

/**
 * The refined career-pivot plan, built on the preferences page and
 * stored in users.pivot_brief. Drives job search + resume tailoring
 * when pivot_enabled is true.
 */
export interface PivotBrief {
  /** The user's raw description of the pivot they want. */
  goal: string;
  /** The 2 clarifying questions Claude asked + the user's answers. */
  qa: { question: string; answer: string }[];
  /** Human-readable summary of the agreed pivot plan (shown back to user). */
  refinedSummary: string;
  /** Short keyword phrase fed to the job-search APIs. */
  searchQuery: string;
  /** A role-family id (see role-families.ts), or null if none fits. */
  suggestedRoleFamily: string | null;
}

/**
 * A weekly LinkedIn coaching brief — generated by Claude, served to the
 * user in /boost. Four pieces that work together: one post they could
 * write, one concrete profile move, two communities to consider, one
 * timing tip. Nothing is auto-posted; the user acts manually.
 */
export interface BoostBrief {
  postIdea: {
    topic: string;
    angle: string;
    draftMarkdown: string;
  };
  profileNudge: {
    action: string;
    how: string;
  };
  groupSuggestions: { name: string; whyItFits: string }[];
  timingTip: {
    day: string;
    timeWindow: string;
    rationale: string;
  };
}

export interface TailoredJobMatch {
  job: JobPosting;
  matchPercent: number;
  reasons: string[];
  tailored: TailoredResume;
  tailoredResumeUrl?: string;     // URL to the polished resume PDF in user's Drive
  tailoredResumeDocUrl?: string;  // URL to the editable resume .docx
  coverLetter?: CoverLetter;      // the tailored cover-letter content
  coverLetterUrl?: string;        // URL to the cover-letter PDF
  coverLetterDocUrl?: string;     // URL to the editable cover-letter .docx
  referrers: Referrer[];        // legacy — populated only if a LinkedIn data API is wired
  /** Pre-built LinkedIn people-search URL — opens 2nd-degree connections at the target company. Free alternative to Proxycurl/Apollo. */
  connectionsSearchUrl?: string;
  inmailDraft?: { subject: string; body: string };
  expectedCtc?: string;
}
