-- ============================================================
-- Relaunch — migration 0008: LinkedIn Boost (paid add-on)
-- ============================================================
-- A weekly coaching brief for each user: one tailored post idea,
-- one profile-improvement nudge, two community suggestions, and a
-- timing tip. Generated by Claude, never auto-posted — the user
-- always acts manually on LinkedIn itself.
-- ============================================================

-- Add-on subscription state. boost_enabled flips on when the user opts
-- in to the paid add-on; boost_until tracks the current billing period
-- end. Trial users are entitled separately (via users.free_until) so
-- these stay null for them.
alter table public.users
  add column if not exists boost_enabled boolean default false,
  add column if not exists boost_until   timestamptz;

-- One brief per user per ISO week (Monday-anchored).
create table if not exists public.boost_briefs (
  id                uuid primary key default uuid_generate_v4(),
  user_id           uuid not null references public.users(id) on delete cascade,
  week_starting     date not null,
  post_idea         jsonb,
  profile_nudge     jsonb,
  group_suggestions jsonb,
  timing_tip        jsonb,
  generated_at      timestamptz default now() not null,
  unique (user_id, week_starting)
);

create index if not exists boost_briefs_user_week_idx
  on public.boost_briefs(user_id, week_starting desc);

alter table public.boost_briefs enable row level security;

-- Users can read their own briefs (admin/cron writes via service role).
create policy "boost_self_read"
  on public.boost_briefs for select
  using (auth.uid() = user_id);
